# Generated by Django 5.2.9 on 2025-12-22 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название модели')),
                ('slug', models.SlugField(verbose_name='Слаг модели')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели товаров',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Иконка')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store_onlayn.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество товара')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг товара')),
                ('price', models.IntegerField(default=100000, verbose_name='Цена товара')),
                ('color_name', models.CharField(default='Белый', max_length=70, verbose_name='Название цвета')),
                ('color_code', models.CharField(default='#ffffff', max_length=20, verbose_name='Код цвета')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка на товар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store_onlayn.category', verbose_name='Категории')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_products', to='store_onlayn.modelproduct', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка и модель')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('screen_resolution', models.CharField(max_length=20, verbose_name='Разрешение экрана')),
                ('battery_capacity', models.CharField(max_length=20, verbose_name='Ёмкость аккумулятора')),
                ('cpu_model', models.CharField(max_length=50, verbose_name='Тип процессора')),
                ('gpu', models.CharField(max_length=50, verbose_name='Графический контроллер')),
                ('hdd', models.CharField(max_length=20, verbose_name='Жесткий диск (HDD)')),
                ('cpu_frequency', models.CharField(max_length=20, verbose_name='Частота процессора')),
                ('screen_size', models.CharField(max_length=10, verbose_name='Диагональ экрана')),
                ('ram', models.CharField(max_length=20, verbose_name='Оперативная память (RAM)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laptop', to='store_onlayn.product')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
            },
        ),
        migrations.CreateModel(
            name='ImagesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store_onlayn.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото товаров',
            },
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка и модель')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('body_material', models.CharField(max_length=100, verbose_name='Корпус')),
                ('technologies', models.TextField(verbose_name='Технологии')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refrigerator', to='store_onlayn.product')),
            ],
            options={
                'verbose_name': 'Холодильник',
                'verbose_name_plural': 'Холодильники',
            },
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_material', models.CharField(max_length=50, verbose_name='Материал корпуса')),
                ('type_of_phone', models.CharField(default='smartphone', max_length=50, verbose_name='Тип телефона')),
                ('sim_type', models.CharField(max_length=20, verbose_name='Тип SIM-карты')),
                ('processor', models.CharField(max_length=100, verbose_name='Тип процессора')),
                ('cpu_cores', models.IntegerField(verbose_name='Количество ядер процессора')),
                ('ram', models.CharField(max_length=20, verbose_name='Объём оперативной памяти')),
                ('storage', models.CharField(max_length=20, verbose_name='Объём встроенной памяти')),
                ('screen_size', models.CharField(max_length=15, verbose_name='Диагональ экрана')),
                ('screen_resolution', models.CharField(max_length=20, verbose_name='Разрешение экрана')),
                ('display_type', models.CharField(max_length=50, verbose_name='Тип дисплея')),
                ('refresh_rate', models.IntegerField(verbose_name='Частота смены кадров, Гц')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smartphone', to='store_onlayn.product')),
            ],
            options={
                'verbose_name': 'детали смартфона',
                'verbose_name_plural': 'Смартфоны',
            },
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка и модель')),
                ('screen_size', models.CharField(max_length=20, verbose_name='Размер (Диагональ)')),
                ('body_material', models.CharField(max_length=50, verbose_name='Корпус')),
                ('technologies', models.CharField(max_length=100, verbose_name='Технологии')),
                ('aspect_ratio', models.CharField(max_length=10, verbose_name='Формат экрана')),
                ('refresh_rate', models.CharField(max_length=20, verbose_name='Частота обновления экрана')),
                ('supported_formats', models.CharField(max_length=200, verbose_name='Поддерживаемые форматы')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tv', to='store_onlayn.product')),
            ],
            options={
                'verbose_name': 'Телевизор',
                'verbose_name_plural': 'Телевизоры',
            },
        ),
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('display', models.CharField(max_length=50, verbose_name='Дисплей')),
                ('spin_speed', models.PositiveSmallIntegerField(verbose_name='Максимальная скорость отжима (об/мин)')),
                ('noise_level', models.CharField(max_length=20, verbose_name='Уровень шума (стирка / отжим)')),
                ('loading_type', models.CharField(max_length=20, verbose_name='Тип загрузки')),
                ('dimensions', models.CharField(max_length=30, verbose_name='Габариты (ШxГxВ)')),
                ('country', models.CharField(max_length=50, verbose_name='Страна производитель')),
                ('max_load', models.CharField(max_length=10, verbose_name='Максимальная загрузка')),
                ('water_consumption', models.CharField(max_length=20, verbose_name='Расход воды за стирку')),
                ('inverter_motor', models.CharField(max_length=50, verbose_name='Инверторный мотор')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='washing_machine', to='store_onlayn.product')),
            ],
            options={
                'verbose_name': 'Стиральная машина',
                'verbose_name_plural': 'Стиральные машины',
            },
        ),
    ]
