# Generated by Django 5.2.9 on 2025-12-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_onlayn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refrigerator',
            name='product',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='product',
        ),
        migrations.RemoveField(
            model_name='washingmachine',
            name='product',
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_onlayn.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_onlayn.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store_onlayn.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Refrigerator',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
        migrations.DeleteModel(
            name='TV',
        ),
        migrations.DeleteModel(
            name='WashingMachine',
        ),
    ]
