# Generated by Django 5.2.9 on 2025-12-28 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_onlayn', '0002_remove_refrigerator_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Характеристику и категорию', 'verbose_name_plural': 'Характеристика и категория'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Характеристику', 'verbose_name_plural': 'Характеристика'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_onlayn.category', verbose_name='Категория характеристки'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название характеристики'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_onlayn.attribute', verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='store_onlayn.product', verbose_name='Аттрибут'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дом/Корпус')),
                ('flat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Квартира')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар покапутеля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупателя',
                'verbose_name_plural': 'Покапутелю',
            },
        ),
    ]
