# Generated by Django 5.2.9 on 2026-01-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_onlayn', '0004_favoriteproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_onlayn.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Корзину',
                'verbose_name_plural': 'Корзины покупателя',
            },
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='В количестве')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_onlayn.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_onlayn.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в корзину',
                'verbose_name_plural': 'Товар корзин',
            },
        ),
    ]
