# Generated by Django 5.2.9 on 2026-01-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_onlayn', '0005_cart_productcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
