# Generated by Django 5.2.9 on 2026-01-11 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_onlayn', '0007_alter_productcart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер получателя')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя покупателя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия покупателя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта покупателя')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарии к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата офорормление доставки')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Адрес')),
                ('status', models.BooleanField(default=False, verbose_name='Статус доставки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_onlayn.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Доставку',
                'verbose_name_plural': 'Доставки',
            },
        ),
    ]
