# Generated by Django 5.2.9 on 2026-01-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_onlayn', '0009_order_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='cart_total_price',
            field=models.IntegerField(default=0, verbose_name=' Обшая сумма'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store_onlayn.order', verbose_name='Заказ'),
        ),
    ]
