# Generated by Django 5.2.9 on 2026-02-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_onlayn', '0010_productorder_cart_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='color',
            field=models.CharField(default='Цвета нет', verbose_name='Цвет продукта'),
        ),
    ]
