# Generated by Django 5.2.9 on 2026-02-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_onlayn', '0011_productorder_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='color_name',
            field=models.CharField(default='Цвет не указан', verbose_name='Название цвета продукта'),
        ),
    ]
