# Generated by Django 5.2.9 on 2026-02-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_onlayn', '0012_productorder_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='color_name',
            field=models.CharField(default='Цвет не указан', max_length=100, verbose_name='Название цвета продукта'),
        ),
    ]
